---
#Main installation actions
#https://clickhouse.com/docs/en/getting-started/#installation

- name: Install ClickHouse RPM package
  yum:
    name: "{{ clickhouse_rpm_package }}"
    state: present
  become: true
  tags: [install]

- name: Hold specified version during YUM upgrade
  become: true
  copy:
    dest: "/etc/yum.repos.d/fixed-{{ item }}"
    content: |
      [{{ item }}]
      name=Fixed version for {{ item }}
      baseurl=file:///etc/yum.repos.d/
      enabled=1
      gpgcheck=0
  loop: "{{ clickhouse_rpm_package }}"

- name: Install by YUM | Ensure clickhouse package installed (latest)
  yum:
    name: "{{ clickhouse_package }} "
    state: "{{ clickhouse_version }}"
    disable_gpg_check: true
  become: true
  tags: [install]
  when: clickhouse_version == 'latest'

- name: Install by YUM | Ensure clickhouse package installed (version {{ clickhouse_version }})
  yum:
    name: "{{ clickhouse_package | map('regex_replace', '$', '-' + clickhouse_version) | list }}"
    state: present
    disable_gpg_check: true
  become: true
  tags: [install]
  when: clickhouse_version != 'latest'
